movie/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,FileField,TextAreaField,SelectField,SelectMultipleField
from wtforms.validators import DataRequired,ValidationError,EqualTo,Email,Regexp

from movie.models import User
class RegistForm(FlaskForm):
    name = StringField(
    label="昵称",
    validators=[
    DataRequired("昵称不能为空！")
    ],
    description="昵称",
    render_kw={
    "class": "form-control input-lg",
    "placeholder": "请输入昵称！",
    }
    )
    email = StringField(
    label="邮箱",
    validators=[
    DataRequired("邮箱不能为空！"),
    Email("邮箱格式不正确！")
    ],
    description="邮箱",
    render_kw={
    "class": "form-control input-lg",
    "placeholder": "请输入邮箱！",
    }
    )
    phone = StringField(
    label="手机",
    validators=[
    DataRequired("手机号不能为空！"),
    Regexp("1[3458]\\d{9}", message="手机格式不正确！")
    ],
    description="手机",
    render_kw={
    "class": "form-control input-lg",
    "placeholder": "请输入手机！",
    }
    )
    pwd = PasswordField(
    label="密码",
    validators=[
    DataRequired("密码不能为空！")
    ],
    description="密码",
    render_kw={
    "class": "form-control input-lg",
    "placeholder": "请输入密码！",
    }
    )
    repwd = PasswordField(
    label="确认密码",
    validators=[
    DataRequired("请输入确认密码！"),
    EqualTo('pwd', message="两次密码不一致！")
    ],
    description="确认密码",
    render_kw={
    "class": "form-control input-lg",
    "placeholder": "请输入确认密码！",
    }
    )
    submit = SubmitField(
    '注册',
    render_kw={
    "class": "btn btn-lg btn-success btn-block",
    }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError("昵称已经存在！")

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在！")

    def validate_phone(self, field):
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError("手机号码已经存在！")

class LoginForm(FlaskForm):
    name = StringField(
    label="账号",
    validators=[
    DataRequired("账号不能为空！")
    ],
    description="账号",
    render_kw={
    "class": "form-control input-lg",
    "placeholder": "请输入账号！",
    }
    )
    pwd = PasswordField(
    label="密码",
    validators=[
    DataRequired("密码不能为空！")
    ],
    description="密码",
    render_kw={
    "class": "form-control input-lg",
    "placeholder": "请输入密码！",
    }
    )
    submit = SubmitField(
    '登录',
    render_kw={
    "class": "btn btn-lg btn-primary btn-block",
    }
    )

class UserdetailForm(FlaskForm):
    name = StringField(
    label="账号",
    validators=[
    DataRequired("账号不能为空！")
    ],
    description="账号",
    render_kw={
    "class": "form-control",
    "placeholder": "请输入账号！",
    }
    )
    email = StringField(
    label="邮箱",
    validators=[
    DataRequired("邮箱不能为空！"),
    Email("邮箱格式不正确！")
    ],
    description="邮箱",
    render_kw={
    "class": "form-control",
    "placeholder": "请输入邮箱！",
    }
    )
    phone = StringField(
    label="手机",
    validators=[
    DataRequired("手机号不能为空！"),
    Regexp("1[3458]\\d{9}", message="手机格式不正确！")
    ],
    description="手机",
    render_kw={
    "class": "form-control",
    "placeholder": "请输入手机！",
    }
    )
    face = FileField(
    label="头像",
    validators=[
    DataRequired("请上传头像！")
    ],
    description="头像",
    )
    info = TextAreaField(
    label="简介",
    validators=[
    DataRequired("简介不能为空！")
    ],
    description="简介",
    render_kw={
    "class": "form-control",
    "rows": 10
    }
    )
    submit = SubmitField(
    '保存修改',
    render_kw={
    "class": "btn btn-success",
    }
    )

class PwdForm(FlaskForm):
    old_pwd = PasswordField(
    label="旧密码",
    validators=[
    DataRequired("旧密码不能为空！")
    ],
    description="旧密码",
    render_kw={
    "class": "form-control",
    "placeholder": "请输入旧密码！",
    }
    )
    new_pwd = PasswordField(
    label="新密码",
    validators=[
    DataRequired("新密码不能为空！"),
    ],
    description="新密码",
    render_kw={
    "class": "form-control",
    "placeholder": "请输入新密码！",
    }
    )
    submit = SubmitField(
    '修改密码',
    render_kw={
    "class": "btn btn-success",
    }
    )


class CommentForm(FlaskForm):
    content = TextAreaField(
        label="内容",
        validators=[
            DataRequired("请输入内容！"),
        ],
        description="内容",
        render_kw={"id": "input_content"
        }
    )
    submit = SubmitField('提交评论',
        render_kw={ "class": "btn btn-success",
                    "id": "btn-sub"
        })

movie/__init__.py
from flask import Flask,render_template
from flask_redis import FlaskRedis
import os
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()
from .models import  *
def create_app():
    app = Flask(__name__)
    app.debug=True

    from movie.home import home as home_blueprint
    from movie.admin import admin as admin_blueprint
    app.register_blueprint(home_blueprint)
    app.register_blueprint(admin_blueprint,url_prefix='/admin')


    app.config['SQLALCHEMY_DATABASE_URI'] = "mysql+pymysql://root:chis1chang@127.0.0.1:3306/movie1?charset=utf8"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    app.config['SQLALCHEMY_POOL_SIZE'] = 10
    app.config['SQLALCHEMY_MAX_OVERFLOW'] = 5
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    app.config['SQLALCHEMY_COMMIT_TEARDOWN'] = True
    db.init_app(app)
    app.config['SECRET_KEY'] = '123456'

    app.config["UP_DIR"] = os.path.join(os.path.abspath(os.path.dirname(__file__)), "static","uploads")
    app.config["FC_DIR"] = os.path.join(os.path.abspath(os.path.dirname(__file__)), "static", "fcloads")
    @app.errorhandler(404)
    def page_not_found(error):
        """
        404
        """
        return render_template("home/404.html"), 404

    app.config["REDIS_URL"] = "redis://127.0.0.1:6379/0"
    rd = FlaskRedis(app)
    app.config['rd']=rd
    return app

movie/admin/__init__.py
from flask import Blueprint
admin = Blueprint('admin',__name__)

from movie.admin import views

movie/admin/views.py
from .import admin
from flask import render_template,redirect,session,url_for,flash,sessions,request,abort


@admin.context_processor
def tpl_extra():
    """
    上下应用处理器
    """
    data = dict(
    online_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )
    return data


from functools import wraps
def admin_login_req(f):
    """
    登录装饰器
    """
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "admin" not in session:
            return redirect(url_for("admin.login", next=request.url))
        return f(*args, **kwargs)

    return decorated_function


# def admin_auth(f):
#     @wraps(f)
#     def decorate_function(*args, **kwargs):
#         # 权限查询
#         abort(404)
#         return f(*args, **kwargs)
#
#     return decorate_function

def admin_auth(f):
    """
    权限控制装饰器
    """
    @wraps(f)
    def decorated_function(*args, **kwargs):
        admin = Admin.query.join(
        Role
        ).filter(
        Role.id == Admin.role_id,
        Admin.id == session["admin_id"]
        ).first()
        auths = admin.role.auths
        # 将原本存储的权限字符串转换为列表
        auths = list(map(lambda v: int(v), auths.split(",")))
        auth_list = Auth.query.all()
        urls = [v.url for v in auth_list for val in auths if val == v.id]
        rule = request.url_rule
        if str(rule) not in urls:
            abort(404)
        return f(*args, **kwargs)

    return decorated_function

from flask import current_app,g
from movie.admin.forms import LoginForm
from movie.models import Admin,Adminlog
@admin.route("/login/",methods=['POST','GET'])
def login():
    """
    后台登录
    """
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        admin = Admin.query.filter_by(name=data["account"]).first()
        #g.logo = os.path.join(current_app.static_folder, 'admin','dist','img','user1-160x160.jpg')
        #print(g.logo)
        #g.logo = 'user1-160x160.jpg'
        from movie import create_app
        print('aaa',dir(create_app))
        if not admin.check_pwd(data["pwd"]):
            flash("密码错误!")
            return redirect(url_for("admin.login"))
        # 如果是正确的，就要定义session的会话进行保存。
        session["admin"] = data["account"]
        session["admin_id"] = admin.id
        session['logo']='user2-160x160.jpg'

        adminlog = Adminlog(
            admin_id=admin.id,
            ip=request.remote_addr,
        )
        db.session.add(adminlog)
        db.session.commit()

        return redirect(request.args.get("next") or url_for("admin.index"))
    return render_template("admin/login.html",form=form)
'''from werkzeug.security import generate_password_hash

    admin = Admin(
        name="mtianyan",
        pwd=generate_password_hash("123456")
'''


@admin.route("/logout/")
def logout():
    """
    后台注销登录
    """
    session.pop("admin", None)
    session.pop('admin_id',None)
    return redirect(url_for("admin.login"))


@admin.route("/")
def index():
    return render_template("admin/index.html")

from .forms import PwdForm
@admin.route("/pwd/", methods=["GET", "POST"])
@admin_login_req
def pwd():
    """
    后台密码修改
    """
    form = PwdForm()
    # 有下面这两句才有错误信息提示
    if form.validate_on_submit():
        data = form.data
        admin = Admin.query.filter_by(name=session["admin"]).first()
        from werkzeug.security import generate_password_hash
        admin.pwd = generate_password_hash(data["new_pwd"])
        db.session.add(admin)
        db.session.commit()
        flash("修改密码成功，请重新登录！", "ok")
        return redirect(url_for('admin.logout'))
    return render_template("admin/pwd.html",form=form)

from .forms import TagForm
from movie.models import Tag,Oplog
from movie import db
@admin.route("/tag/add/",methods=['POST','GET'])
@admin_login_req
def tag_add():
    """
    标签添加与编辑
    """
    form = TagForm()
    if form.validate_on_submit():
        data=form.data
        tag = Tag.query.filter_by(name=data["name"]).count()
        if tag == 1:
            flash("标签已存在", "err")
            return redirect(url_for("admin.tag_add"))
        tag = Tag(
            name=data["name"]
        )
        db.session.add(tag)
        db.session.commit()
        flash("标签添加成功", "ok")
        oplog = Oplog(
            admin_id=session["admin_id"],
            ip=request.remote_addr,
            reason="添加标签%s" % data["name"]
        )
        db.session.add(oplog)
        db.session.commit()
    return render_template("admin/tag_add.html", form=form)


@admin.route("/tag/list/<int:page>/", methods= ["GET"])
@admin_login_req
@admin_auth
def tag_list(page=None):
    """
    标签列表
    """
    if page is None:
        page = 1
    page_data = Tag.query.order_by(
    Tag.addtime.desc()
    ).paginate(page=page, per_page=2)
    return render_template("admin/tag_list.html", page_data=page_data)
@admin.route("/tag/del/<int:id>/", methods= ["GET"])
@admin_login_req
def tag_del(id=None):
    """
    标签删除
    """
    # filter_by在查不到或多个的时候并不会报错，get会报错。
    tag = Tag.query.filter_by(id=id).first_or_404()
    db.session.delete(tag)
    db.session.commit()
    flash("标签<<{0}>>删除成功".format(tag.name), "ok")
    return redirect(url_for("admin.tag_list", page=1))

@admin.route("/tag/edit/<int:id>", methods=["GET", "POST"])
@admin_login_req
def tag_edit(id=None):
    """
    标签编辑
    """
    form = TagForm()
    form.submit.label.text = "编辑"
    tag = Tag.query.get_or_404(id)
    if form.validate_on_submit():
        data = form.data
        tag_count = Tag.query.filter_by(name=data["name"]).count()
    # 说明已经有这个标签了,此时向添加一个与其他标签重名的标签。
        if tag.name != data["name"] and tag_count == 1:
            flash("标签已存在", "err")
            return redirect(url_for("admin.tag_edit", id=tag.id))
        tag.name = data["name"]
        db.session.add(tag)
        db.session.commit()
        flash("标签修改成功", "ok")
        redirect(url_for("admin.tag_edit", id=tag.id))
    return render_template("admin/tag_edit.html", form=form, tag=tag)

from werkzeug.utils import secure_filename
import os,uuid
from datetime import datetime
# 修改文件名称
def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.now().strftime("%Y%m%d%H%M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename

from .forms import MovieForm
from flask import  current_app
from movie.models import Movie
@admin.route("/movie/add/", methods=["GET", "POST"])
def movie_add():
    """
    编辑电影页面
    """
    form = MovieForm()
    if form.validate_on_submit():
        data = form.data
        file_url = secure_filename(form.url.data.filename)
        file_logo = secure_filename(form.logo.data.filename)
        if not os.path.exists(current_app.config["UP_DIR"]):
            # 创建一个多级目录
            os.makedirs(current_app.config["UP_DIR"])
            #print('_______',current_app.config["UP_DIR"])
            import  sys, stat
            import platform
            #因为windows chmod方法第一次改变文件夹读写时会异常报错，所以修改为判断平台方式
            osName = platform.system()
            if (osName == 'Windows'):
                os.chmod(current_app.config["UP_DIR"], stat.S_IWRITE and stat.S_IREAD)
            else:
                os.chmod(current_app.config["UP_DIR"], "rw")
        url = change_filename(file_url)
        logo = change_filename(file_logo)
        # 保存
        form.url.data.save(os.path.join(current_app.config["UP_DIR"] , url))
        form.logo.data.save(os.path.join(current_app.config["UP_DIR"] , logo))
        # url,logo为上传视频,图片之后获取到的地址
        movie = Movie(
            title=data["title"],
            url=url,
            info=data["info"],
            logo=logo,
            star=int(data["star"]),
            tag_id=int(data["tag_id"]),
            playnum=0,
            commentnum=0,
            area=data["area"],
            release_time=data["release_time"],
            length=data["length"]
        )
        db.session.add(movie)
        db.session.commit()
        flash("添加电影成功！", "ok")
        return redirect(url_for('admin.movie_add'))
    return render_template("admin/movie_add.html", form=form)


@admin.route("/movie/list/<int:page>",methods=['GET','POST'])
def movie_list(page=None):
    """
    电影列表页面
    """
    if page is None:
        page = 1
    page_data = Movie.query.join(Tag).filter(Tag.id == Movie.tag_id).order_by(Movie.addtime.desc()).paginate(page = page,per_page=1)

    return render_template("admin/movie_list.html",page_data=page_data)

@admin.route("/movie/del/<int:id>",methods=['GET'])
def movie_del(id=None):
    """
    电影列表页面
    """
    movie = Movie.query.get_or_404(id)
    db.session.delete(movie)
    db.session.commit()
    flash('电源删除成功','ok')

    return redirect(url_for("admin.movie_list",page=1))

@admin.route("/movie/edit/<int:id>/", methods=["GET", "POST"])
@admin_login_req
def movie_edit(id=None):
    """
    编辑电影页面
    """
    form = MovieForm()
    form.url.validators = []
    form.logo.validators = []
    movie = Movie.query.get_or_404(int(id))
    if request.method == "GET":
        form.info.data = movie.info
        form.tag_id.data = movie.tag_id
        form.star.data = movie.star
    if form.validate_on_submit():
        data = form.data
        movie_count = Movie.query.filter_by(title=data["title"]).count()
        # 存在一步名字叫这个的电影，有可能是它自己，也有可能是同名。如果是现在的movie不等于要提交的数据中title。那么说明有两个。
        if movie_count == 1 and movie.title != data["title"]:
            flash("片名已经存在！", "err")
            return redirect(url_for('admin.movie_edit', id=id))
        # 创建目录
        if not os.path.exists(current_app.config["UP_DIR"]):
            os.makedirs(current_app.config["UP_DIR"])
            #os.chmod(current_app.config["UP_DIR"], "rw")
            import platform,stat
            osName = platform.system()
            if (osName == 'Windows'):
                os.chmod(current_app.config["UP_DIR"], stat.S_IWRITE and stat.S_IREAD)
            else:
                os.chmod(current_app.config["UP_DIR"], "rw")
        # 上传视频
        if form.url.data != "":

movie/home/__init__.py
from flask import Blueprint

home = Blueprint('home',__name__)
import movie.home.views

movie/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css')}}">

{% block css %} {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index') }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="{{ url_for('home.search',page=1)}}"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js')}}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js')}}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>

{% block js %}
{% endblock %}

</body>
</html>

movie/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css')}}">

{% block css %} {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index') }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id = "do_search" href="{{ url_for('home.search',page=1)}}"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js')}}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js')}}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect:'fadeIn'
        });
        $("#do_search").click(function () {
            var key = $("#key_movie").val()
            location.href = "{{ url_for('home.search',page=1) }}?key="+key
        })

    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>

{% block  js %}
{% endblock %}

</body>
</html>

movie/templates/home/menu.html
<div class="col-md-3">
        <div class="list-group">
            <a id="m1" href="{{  url_for('home.user') }}" class="list-group-item ">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
             <a id="m2" href="{{  url_for('home.pwd') }}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a id="m3" href="{{  url_for('home.comments',page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
            <a id="m4" href="{{  url_for('home.loginlog',page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
            </a>
            <a id="m5" href="{{  url_for('home.moviecol',page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
            </a>
        </div>
    </div>